apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: cxtoemv23-md-normal
  namespace: cxtoemv23
spec:
  template:
    spec:
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.large
      sshKeyName: tks-seoul
      rootVolume:
        size: 50
        type: gp2
      subnet:
        filters:
        - name: "tag:sigs.k8s.io/cluster-api-provider-aws/role"
          values:
          - "private"
        - name: "tag:Name"
          values:
          - "*cxtoemv23*"
